# Generated by Django 3.0.6 on 2020-06-03 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortcourse_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavereportinstructors',
            name='leave_status',
            field=models.IntegerField(default=0),
        ),
    ]
