# Generated by Django 3.0.6 on 2020-06-08 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortcourse_app', '0002_auto_20200603_0713'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='registration',
        ),
        migrations.AddField(
            model_name='customuser',
            name='password',
            field=models.CharField(default=1, max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attendance',
            name='attendance_date',
            field=models.DateField(),
        ),
    ]
