# Generated by Django 3.0.6 on 2020-06-18 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shortcourse_app', '0004_auto_20200610_1345'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentResult',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('course_exam_marks', models.FloatField(default=0)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
                ('batch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shortcourse_app.Batch')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shortcourse_app.Students')),
            ],
        ),
    ]
