# Generated by Django 3.0.8 on 2020-10-11 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortcourse_app', '0005_studentresult'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='full_name',
        ),
    ]
