# Generated by Django 3.0.8 on 2020-10-14 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortcourse_app', '0007_onlineclassroom'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OnlineClassRoom',
        ),
    ]
