# Generated by Django 3.0.8 on 2020-10-19 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortcourse_app', '0008_delete_onlineclassroom'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subjects',
        ),
    ]
